### ISSUE TITLE
Rotary Encoder support?

### ISSUE THREAD

**Issue by djensenius** [stianeikeland/go-rpio#52]
Are there any plans for rotary encoder support?

**Comment by drahoslove** [comment]
@djensenius What kind of support would you like to see?

I believe you might be already able to use what `go-rpio` offers you to support your rotary encoder (with your custom implementation).

Does `go-rpio` lack any crucial feature which prevents you from doing so? If so please specify.

Anyway, any specific implementation to support any specific peripheral device would be too specific to be part of `go-rpio`. We might try to support some general interfaces, like SPI, I2C etc..  but not specific devices - that is up to the users.

**Comment by djensenius** [comment]
Thanks @drahoslove - this makes sense!
