### ISSUE TITLE
strangely, does *not* work with sudo

### ISSUE THREAD

**Issue by dubaxx** [stianeikeland/go-rpio#61]
I'm having a very strange issue here, hopefully someone can shed some light on the subject.

go 1.14, raspberry pi 4 B+

using the blinker.go example:

./blinker works just fine
sudo ./blinker makes nothing happen.

Why is this?  Normally that would be fine, except that I'm trying to use rpio along with a dht11 library that requires root access to run.  I find it perplexing that running rpio with heightened privileges causes it to _not_ work.

**Comment by srmihalampret** [comment]
Same here - had to switch from `root` user to `pi` user to get blinker.go working. Not sure what is the reason for this.

**Comment by mlampret** [comment]
Same here - had to switch from `root` user to `pi` user to get blinker.go working. Not sure what is the reason for this.

**Comment by openwrd** [comment]
I also encountered the same problem.

**Comment by drahoslove** [comment]
This might be some OS-related change.
You can try to change this part of code: 
https://github.com/stianeikeland/go-rpio/blob/master/rpio.go#L630-L637

So that `/dev/gpiomem` is always used (but only basic gpio functionality will work)

**Comment by drahoslove** [comment]
Also #50 this might solve your issue, can you please try?

**Comment by s00500** [comment]
Same issue here... can not get it to work on root on and RPI4, go 1.15.3
Only trying to control a single pin at the moment, program works with pi

**Comment by rami-dabain** [comment]
related https://github.com/stianeikeland/go-rpio/issues/68 [fixed]

**Comment by drahoslove** [comment]
Should be fixed now - thanks to #70 by @rami-dabain.

Feel free to reopen or create a new issue in case of a problem.
