### ISSUE TITLE
Errors on go get

### ISSUE THREAD

**Issue by danhardman** [stianeikeland/go-rpio#7]
I get the following output when I get this package. I'm running Windows 10 with go version go1.5.1 windows/amd64

    > go get github.com/stianeikeland/go-rpio
    # github.com/stianeikeland/go-rpio
    ..\..\..\github.com\stianeikeland\go-rpio\rpio.go:290: undefined: syscall.Mmap
    ..\..\..\github.com\stianeikeland\go-rpio\rpio.go:294: undefined: syscall.PROT_READ
    ..\..\..\github.com\stianeikeland\go-rpio\rpio.go:294: undefined: syscall.PROT_WRITE
    ..\..\..\github.com\stianeikeland\go-rpio\rpio.go:295: undefined: syscall.MAP_SHARED
    ..\..\..\github.com\stianeikeland\go-rpio\rpio.go:315: undefined: syscall.Munmap

I assume this has something to do with: https://golang.org/s/go1.4-syscall

**Comment by z26100** [comment]
Try to change goos / gooarch to linux / arm.

**Comment by danhardman** [comment]
That was the problem... Feel like this should be explained in the syscall package for when noobs like me come around!
