### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by elamre** [stianeikeland/go-rpio#73]
Hello, could a new tag be made? So RPI 4 works accordingly. Right now using: 
github.com/stianeikeland/go-rpio/v4 v4.4.1-0.20200705092735-acc952dac3eb
also works for my modules file, but would be nice to have a more common way to approach this

**Comment by drahoslove** [comment]
@elamre I committed some updates and created a new tag - `v4.5.0`.

I think it should solve your issue. Feel free to reopen this if not.
