### ISSUE TITLE
Add support for PWM "Balanced" algorithm (default BCM mode)

### ISSUE THREAD

**Issue by youngkin** [stianeikeland/go-rpio#78]
Looking at SetDutyCycle() the use of mark/space is hard-coded. Is there a reason the default algorithm is being overridden? Would it be possible to add support for explicitly setting which algorithm should be used?

**Comment by youngkin** [comment]
I opened a PR on this several days ago. Do any contributors have time to have a look?

**Comment by youngkin** [comment]
For those interested in this change while it's waiting to be merged ( #79 ), it's available on my fork at https://github.com/youngkin/gpio. The associated _go.mod_ file has been modified so that it's not necessary to modify imports to use that version of go-rpio.

**Comment by drahoslove** [comment]
Hi, youngkin,
To be honest, I'm not sure what was the reason for changing the mode.

I was looking at your pull request and also checked the bcm [reference manual](https://datasheets.raspberrypi.com/bcm2835/bcm2835-peripherals.pdf), 
and I realized, that there is a critical bug in the pwm implementation.

I think the `pwmRngReg` and `pwmDatReg` values are wrong. Should be `3 4` or `6 7` (probably - table 9.6 on page 141 has wrong values in the Address offset column).

I'd like to fix that first, but unfortunately, I'm not in possession of a working Pi.

Do you think you could be so kind and test that and confirm that my assumption is right?

**Comment by youngkin** [comment]
Yikes! I'll double check that against the reference (thought I did that but that's why we do PRs 🙂) That said, it behaves as I expected it would on my Pi 3B+, but I will double check.

**Comment by youngkin** [comment]
Per the  bcm [reference manual](https://www.raspberrypi.org/app/uploads/2012/02/BCM2835-ARM-Peripherals.pdf), page 141, table 9.6, counting up by 4 (i.e., 32 bit words), the register offsets are as follows :

0x0 - CTL
0x4 - STA
0x8 - DMAC
0xC - **_unused_**
0x10 - RNG1 (aka `pwmRngReg`)
0x14 - DAT1 (aka `pwmDatReg`)
0x18 - FIF1
0x1C - **_unused_**
0x20 - RNG2  (aka `pwmRngReg`)
0x24 - DAT2 (aka `pwmDatReg`)

Counting up by words (as the code does):
 
0 - CTL
1 - STA
2 - DMAC
3 - **_unused_**
4 - RNG1
5 - DAT1
6 - FIF1
7 - **_unused_**
8 - RNG2
9 - DAT2

Assuming my hexadecimal counting is correct, the PWM register offsets are 4/5 and 8/9 as in the code (rpio.go, lines 662-667 in my PR, 640-645 in the main branch). I also verified this against the [WiringPi library](https://github.com/WiringPi/WiringPi/blob/master/wiringPi/wiringPi.c), lines 150-153. It also uses these offsets.

So, I think the code is correct.

**Comment by drahoslove** [comment]
> So, I think the code is correct.

Aww, that makes sense. I did not realize the addresses are hex, not decimal. That confused me and I thought the number are wrong because there is [a lot of errors in the document](https://elinux.org/BCM2835_datasheet_errata). I was like "that must be the reason why there are several 'PWM does not work' issues opened."


Apparently, I was smarter 4 years ago than I am now 😄 

Thank you very much and sorry for freaking out 👍

**Comment by youngkin** [comment]
It confused me at first too. I had to brush up on my hexadecimal counting to figure it out :)

**Comment by drahoslove** [comment]
Closed by #79
