### ISSUE TITLE
Input interrupts

### ISSUE THREAD

**Issue by brian-armstrong** [stianeikeland/go-rpio#8]
Hi,

Have you considered adding input interrupts? You can get them from the files exposed by sysfs in /sys/class/gpio. I've made a library which does this at https://github.com/brian-armstrong/gpio

sysfs can also expose i2c and spi if you uncomment the modules in /boot/config.txt and then reboot. This might be an easy way for you to add i2c and spi functionality as well.

**Comment by curiositry** [comment]
@stianeikeland Is this on the roadmap … or should I find a different GPIO library?

**Comment by brian-armstrong** [comment]
@curiositry Try mine, it's linked in my comment :)

**Comment by curiositry** [comment]
@brian-armstrong Thanks, I’ll take a look! I’ve already built this library into my app, though, and I’m hoping I won’t have to abandon it…

**Comment by stianeikeland** [comment]
I'm afraid I don't have time at the moment, but if anyone is willing then a PR is welcome :)

**Comment by brian-armstrong** [comment]
@curiositry If you find my gpio lib lacking anything just let me know :)
